version: '3.9'

services:
  postgres:
    image: postgres:14.10-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=realtyhub
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  typesense:
    image: typesense/typesense:0.25.0
    restart: always
    ports:
      - '8108:8108'
    volumes:
      - typesense_data:/data
    environment:
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_DATA_DIR=/data

  api:
    build:
      context: .
      dockerfile: ./docker/development/api.Dockerfile
    restart: always
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/realtyhub
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_HOST=typesense
      - NODE_ENV=development
    depends_on:
      - postgres
      - typesense

  search-indexer:
    build:
      context: .
      dockerfile: ./docker/development/search-indexer.Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/realtyhub
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_HOST=typesense
      - NODE_ENV=development
    depends_on:
      - postgres
      - typesense

  web:
    build:
      context: .
      dockerfile: ./docker/development/web.Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_TYPESENSE_HOST=localhost
      - NEXT_PUBLIC_TYPESENSE_PORT=8108
      - NEXT_PUBLIC_TYPESENSE_PROTOCOL=http
      - NEXT_PUBLIC_TYPESENSE_API_KEY=xyz
    depends_on:
      - api

volumes:
  postgres_data:
  typesense_data: 