# Main docker-compose.yml - Imports configuration from other files

# Development:
#   docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

# Production:
#   docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

# The files work as follows:
# - docker-compose.base.yml: Contains shared base infrastructure services (db, search, redis)
# - docker-compose.dev.yml: Development-specific service configuration with volumes mounted
# - docker-compose.prod.yml: Production configuration with resource limits
# - docker-compose.override.yml: Automatically loaded in development, contains local overrides

# This main file just imports from docker-compose.base.yml
# You shouldn't need to modify this file directly

version: '3.9'

include:
  - docker-compose.base.yml 